In [1]:
# Univariate Selection
from pandas import read_csv
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

dataframe = read_csv("close_world_data.csv")
array = dataframe.values
X = array[:,0:16]
Y = array[:,80]
test = SelectKBest(score_func=f_classif, k=5)
fit = test.fit(X, Y)
set_printoptions(precision=3)
print(fit.scores_)
features = fit.transform(X)
# summarize selected features
# print(features[0:5,:])

[183.232 148.3   190.791 192.671  70.023 163.688 183.294 145.605 162.175
 124.855 135.23   12.22  163.092 169.677 100.591  64.726]


In [9]:
# Univariate Selection
print(fit.scores_)
print(features[0:5,:])

[183.232 148.3   190.791 192.671  70.023 163.688 183.294 145.605 162.175
 124.855 135.23   12.22  163.092 169.677 100.591  64.726]
[[ 37514691  10070509  10559671 661114306 659626502]
 [ 49901539  15983066  15905409 756436026 841332593]
 [ 50400281  15329054  15610305 734120225 827927127]
 [ 33857600  12144856  12142687 722133401 750020694]
 [ 48650176  16656488  16676601 790604661 801691367]]


In [11]:
# Recursive Feature Elimination
from pandas import read_csv
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
dataframe = read_csv("close_world_data.csv")
array = dataframe.values
X = array[:,0:16]
Y = array[:,80]
Y=Y.astype('int')
model = LogisticRegression(solver='lbfgs')
rfe = RFE(model, 5)
fit = rfe.fit(X, Y)
print("Num Features: %d" % fit.n_features_)
print("Selected Features: %s" % fit.support_)
print("Feature Ranking: %s" % fit.ranking_)

/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:70: FutureWarning: Pass n_features_to_select=5 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "
/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

In

Num Features: 5
Selected Features: [ True False  True  True  True False False False False False False False
 False False  True False]
Feature Ranking: [ 1  8  1  1  1  5  4  2  6  9 11 12 10  7  1  3]


/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [12]:
# Recursive Feature Elimination
print("Num Features: %d" % fit.n_features_)
print("Selected Features: %s" % fit.support_)
print("Feature Ranking: %s" % fit.ranking_)

Num Features: 5
Selected Features: [ True False  True  True  True False False False False False False False
 False False  True False]
Feature Ranking: [ 1  8  1  1  1  5  4  2  6  9 11 12 10  7  1  3]


In [18]:
# Feature Importance with Extra Trees Classifier
from pandas import read_csv
from sklearn.ensemble import ExtraTreesClassifier
dataframe = read_csv("close_world_data.csv")
array = dataframe.values
X = array[:,0:16]
Y = array[:,80]
Y=Y.astype('int')
model = ExtraTreesClassifier(n_estimators=10)
model.fit(X, Y)
print(model.feature_importances_)

[0.068 0.064 0.068 0.061 0.056 0.066 0.079 0.059 0.061 0.059 0.054 0.048
 0.063 0.083 0.059 0.052]


In [19]:
# Feature Importance with Extra Trees Classifier
print(model.feature_importances_)

[0.068 0.064 0.068 0.061 0.056 0.066 0.079 0.059 0.061 0.059 0.054 0.048
 0.063 0.083 0.059 0.052]


In [4]:
index = [0,2,3,6,13]
cols = []
for i in range(5):
    for j in index:
        cols.append(i*16+j)
cols.append(80)
data = dataframe.iloc[:, cols]
data.to_csv("database_close.csv", index=False)

In [6]:
open_dataframe = read_csv("open_world_data.csv")
index = [0,2,3,6,13]
cols = []
for i in range(5):
    for j in index:
        cols.append(i*16+j)
cols.append(80)
data = open_dataframe.iloc[:, cols]
data.to_csv("database_open.csv", index=False)